Day 15.2 =
-- Which customers have purchased only Queso Cabrales on a given order?
VAR __TempTable =
    ADDCOLUMNS (
        SUMMARIZE ( Orders, Customers[CompanyName], Orders[OrderID] ),
        "@Number of Distinct Products", CALCULATE ( COUNT ( Orders[ProductID] ) ),
        "@Product ID", CALCULATE ( SELECTEDVALUE ( Orders[ProductID] ) )
    )
VAR __BoughtOnlyQCCustomers =
    FILTER ( __TempTable, [@Number of Distinct Products] = 1 && [@Product ID] = 11 )
VAR __BoughtOnlyQCCustomersNames =
    CONCATENATEX (
        __BoughtOnlyQCCustomers,
        Customers[CompanyName],
        "
",
        Customers[CompanyName], ASC
    )
RETURN
    __BoughtOnlyQCCustomersNames