Day 24.2 = 
-- Which employees sold over $100K in 2021?
VAR __2021SalesPerEmployee =
    ADDCOLUMNS (
        SUMMARIZE ( Orders, Orders[EmployeeID], Employees[Full Name] ),
        "@Sales", CALCULATE ( [Total Sales], 'Calendar'[Year] = 2021 )
    )
VAR __Over100KEmployees =
    FILTER ( __2021SalesPerEmployee, [@Sales] > 100000 )
VAR __Over100KEmployeesNames =
	CONCATENATEX (
        __Over100KEmployees,
        Employees[Full Name],
        "
",
        Employees[Full Name],
        ASC
    )
RETURN
    __Over100KEmployeesNames