Day 6.2 = 
-- What is the average order size for all years and all customers?
VAR __TotalQty =
    SUMX ( Orders, Orders[Quantity] )
VAR __NumOrders =
    DISTINCTCOUNT ( Orders[OrderID] )
VAR __AverageOrderSize =
    DIVIDE ( __TotalQty, __NumOrders )
RETURN
    __AverageOrderSize